name: carpeek
description: Instantly identify any car with AI - snap a photo and discover make, model, year, specs, and market value
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9

  # Routing
  go_router: ^12.1.3

  # Networking
  dio: ^5.4.0
  retry: ^3.1.2

  # Camera & Media
  camera: ^0.10.5+7
  image_picker: ^1.0.4
  image: ^4.1.3

  # JSON & Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Caching & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Animations & UI
  lottie: ^2.7.0
  transparent_image: ^2.0.1
  cached_network_image: ^3.3.0

  # Image Processing
  image_cropper: ^5.0.1

  # Utilities
  path: ^1.8.3
  uuid: ^4.2.1
  flutter_launcher_icons: ^0.14.4

  # In-app purchases
  in_app_purchase: ^3.2.0

  # URL Launcher
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "carid.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "carid.png"
  remove_alpha_ios: true