name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'

    - name: Install Flutter dependencies
      run: |
        flutter pub get
        flutter --version

    - name: Generate iOS configuration
      run: |
        flutter build ios --config-only --no-codesign

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod --version

    - name: Install iOS dependencies
      run: |
        cd ios
        export FLUTTER_ROOT=$FLUTTER_ROOT
        echo "FLUTTER_ROOT=$FLUTTER_ROOT"
        pod repo update
        pod install --verbose

    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign